r"""
This file has been automatically generated by sasfit_convert and manually edited
by Wojciech Potrzebowski, ESS on 2017-12-07.

The model calculates an empirical functional form for SAS data characterized
by coreshellmicrogel

Definition:
-----------
This model can be used to calculate the scattering from spherical
particles with a parabolic "fuzzy" interface cite{Berndt2005,Berndt2006,Berndt2006a}.
The radial profile is given by

.. math::
ho(r,R,sigma) &=
egin{cases}
1 & mbox{for } rleq R-sigma \
1-frac{1}{2}frac{left((r-R)+sigmaight)^2}{sigma^2} & mbox{for } R-sigma < r leq R \
frac{1}{2}frac{left((R-r)+sigmaight)^2}{sigma^2} & mbox{for } R< rleq R+sigma \
0 & mbox{for } r > leq R+sigma
end{cases}


where $R=W+sigma$. For such a radial profile the Fourier-transformation can be calculated analytically as

.. math::
F(Q,R,sigma) = mathcal{F}[ho(r,R,sigma)] = \
4 pi Bigg(
        left(frac{R}{sigma^2}+frac{1}{sigma}ight) frac{cos (q(R+sigma))}{q^4}
    +   left(frac{R}{sigma^2}-frac{1}{sigma}ight) frac{cos (q(R-sigma))}{q^4} \
    -   3 frac{sin(q(R+sigma))}{q^5 sigma^2}
    -   3 frac{sin(q(R-sigma))}{q^5 sigma^2}
    -   6  frac{sin(qR)}{q^5 sigma^2}
    -   2 R frac{cos(qR)}{q^4 sigma^2}

The last term in the brackets needed to be corrected compared to the papers mentioned above
due to a typo in the original papers.
The radial scattering length density profile of a fuzzy core
shell like in Fig. ef{fig:profile:CoreShellMicrogel}b can be obtained by

.. math::
eta_{core,sh}(r,W_	extrm{core},sigma_	extrm{core},D,sigma_	extrm{sh,in},W_	extrm{sh},sigma_	extrm{sh,out}) =
    eta_	extrm{sol}
+ (eta_	extrm{shell}-eta_	extrm{sol}) ho(r,R_	extrm{out},sigma_	extrm{out}) \
+ (eta_	extrm{shell}-eta_	extrm{sol}) ho(r,R_	extrm{sh,in},sigma_	extrm{sh,in})
+ (eta_	extrm{core} -eta_	extrm{sol}) ho(r,R_	extrm{core},sigma_	extrm{core})

with
.. math::
    R_	extrm{core} &= W_	extrm{core}+sigma_	extrm{core} \
    R_	extrm{sh,in}&= R_	extrm{core}+D \
    R_	extrm{out}  &= R_	extrm{sh,in}+sigma_	extrm{sh,in}+W_	extrm{sh}+sigma_	extrm{sh,out}

In the same way also the scattering amplitude $F_	extrm{core,sh}(Q,cdots)$ and the scattering intensity
$I_	extrm{core,sh}(Q,cdots)=abs{F_	extrm{core,sh}(Q,cdots)}^2$ can be calculated

.. math::
F_	extrm{core,sh}(Q,W_	extrm{core},sigma_	extrm{core},D,sigma_	extrm{sh,in},W_	extrm{sh},sigma_	extrm{sh,out}) =
  (eta_	extrm{shell}-eta_	extrm{sol}) F(Q,R_	extrm{out},sigma_	extrm{out}) \
+ (eta_	extrm{shell}-eta_	extrm{sol}) F(Q,R_	extrm{sh,in},sigma_	extrm{sh,in})
+ (eta_	extrm{core} -eta_	extrm{sol}) F(Q,R_	extrm{core},sigma_	extrm{core})
I_	extrm{core,sh}(Q,W_	extrm{core},sigma_	extrm{core},D,sigma_	extrm{sh,in},W_	extrm{sh},sigma_	extrm{sh,out}) &=
abs{F_	extrm{core,sh}(Q,cdots)}^2

References:
-----------
Author(s) of the original file: src/plugins/fuzzysphere/sasfit_ff_coreshellmicrogel.c
Joachim Kohlbrecher (joachim.kohlbrecher@psi.ch)

https://github.com/SASfit/SASfit/
A paper about SASfit has been published in
J. Appl. Cryst. (2015). 48, 1587-1598
doi:10.1107/S1600576715016544

Ingo Berndt, Jan Skov Pedersen, Peter Lindner, and Walter Richtering.
Influence of shell thickness and cross-link density on the structure of
temperature-sensitive poly-n-isopropylacrylamidepoly-n-isopropylmethacrylamide
coreshell microgels investigated by small-angle neutron scattering.
Langmuir, 22(1):459-468,2006.PMID: 16378460.

Ingo Berndt, Jan Skov Pedersen, and Walter Richtering.
Structure of multiresponsive intelligent? coreshell microgels.
Journal of the American Chemical Society,
127(26):9372-9373, 2005 PMID: 15984856

Ingo Berndt, Jan Skov Pedersen, and Walter Richtering.
Temperature-sensitive coreshell microgel particles with dense shell.
Angewandte Chemie, 118(11):1769-1773, 2006.
"""
from numpy import inf

name = "coreshellmicrogel"
title = " "
description = ""
category = "shape-independent"
#pylint: disable=bad-whitespace, line-too-long
parameters = [
 [ "W_CORE", 	"", 	10.0, 	[-inf, inf], 	"volume", 	"radius of center parts of core Wcore with homogeneous scattering length density"],
 [ "SIGMA_CORE", 	"", 	3.0, 	[-inf, inf], 	"volume", 	"interface half width of the core"],
 [ "W_SH", 	"", 	4, 	[-inf, inf], 	"volume", 	"width of center parts of shell Wsh with homogeneous scattering length density"],
 [ "SIGMA_SHIN", 	"", 	3, 	[-inf, inf], 	"volume", 	"half width of the inner interface of shell"],
 [ "D", 	"", 	3.0, 	[-inf, inf], 	"volume", 	"distance between interface of core and in interface of shell"],
 [ "SIGMA_OUT", 	"", 	4.0, 	[-inf, inf], 	"volume", 	"half width of the outer surface profile"],
 [ "ETA_CORE", 	"", 	3.5, 	[-inf, inf], 	"", 	"scattering length density of homogeneous core part"],
 [ "ETA_SHELL", 	"", 	2.5, 	[-inf, inf], 	"", 	"scattering length density of homogeneous shell part "],
 [ "ETA_SOL", 	"", 	1.0, 	[-inf, inf], 	"", 	"scattering length density of solvent"],
]
 #pylint: enable=bad-whitespace, line-too-long

source = ["sas_pow.c","sasfit_coreshellmicrogel.c" ]

single = False

demo = dict(
	W_CORE = 10.0,
	SIGMA_CORE = 3.0,
	W_SH = 4.0,
	SIGMA_SHIN = 3.0,
	D = 3.0,
	SIGMA_OUT = 4.0,
	ETA_CORE = 3.5,
	ETA_SHELL = 2.5,
	ETA_SOL = 1.0)

tests = [[{}, 0.001, 120157.969934],
         [{}, 0.2, 303.628432595],
         [{}, [0.2], [303.628432595]]
        ]
